name: Testing jest
on: [push]
jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use appropriate node version
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # yarn install

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test # yarn test
